/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContentElementsRouteImport } from './routes/content-elements'
import { Route as OurStaffRouteImport } from './routes/our-staff'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingTablesRouteImport } from './routes/pricing-tables'
import { Route as RecipesGridRouteImport } from './routes/recipes-grid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentElementsRoute = ContentElementsRouteImport.update({
  id: '/content-elements',
  path: '/content-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStaffRoute = OurStaffRouteImport.update({
  id: '/our-staff',
  path: '/our-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingTablesRoute = PricingTablesRouteImport.update({
  id: '/pricing-tables',
  path: '/pricing-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesGridRoute = RecipesGridRouteImport.update({
  id: '/recipes-grid',
  path: '/recipes-grid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/content-elements': typeof ContentElementsRoute
  '/our-staff': typeof OurStaffRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing-tables': typeof PricingTablesRoute
  '/recipes-grid': typeof RecipesGridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/content-elements': typeof ContentElementsRoute
  '/our-staff': typeof OurStaffRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing-tables': typeof PricingTablesRoute
  '/recipes-grid': typeof RecipesGridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/content-elements': typeof ContentElementsRoute
  '/our-staff': typeof OurStaffRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing-tables': typeof PricingTablesRoute
  '/recipes-grid': typeof RecipesGridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blog'
    | '/content-elements'
    | '/our-staff'
    | '/portfolio'
    | '/pricing-tables'
    | '/recipes-grid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/blog'
    | '/content-elements'
    | '/our-staff'
    | '/portfolio'
    | '/pricing-tables'
    | '/recipes-grid'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/blog'
    | '/content-elements'
    | '/our-staff'
    | '/portfolio'
    | '/pricing-tables'
    | '/recipes-grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BlogRoute: typeof BlogRoute
  ContentElementsRoute: typeof ContentElementsRoute
  OurStaffRoute: typeof OurStaffRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingTablesRoute: typeof PricingTablesRoute
  RecipesGridRoute: typeof RecipesGridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-elements': {
      id: '/content-elements'
      path: '/content-elements'
      fullPath: '/content-elements'
      preLoaderRoute: typeof ContentElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-staff': {
      id: '/our-staff'
      path: '/our-staff'
      fullPath: '/our-staff'
      preLoaderRoute: typeof OurStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-tables': {
      id: '/pricing-tables'
      path: '/pricing-tables'
      fullPath: '/pricing-tables'
      preLoaderRoute: typeof PricingTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes-grid': {
      id: '/recipes-grid'
      path: '/recipes-grid'
      fullPath: '/recipes-grid'
      preLoaderRoute: typeof RecipesGridRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BlogRoute: BlogRoute,
  ContentElementsRoute: ContentElementsRoute,
  OurStaffRoute: OurStaffRoute,
  PortfolioRoute: PortfolioRoute,
  PricingTablesRoute: PricingTablesRoute,
  RecipesGridRoute: RecipesGridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
