/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as OurStaffRouteImport } from './routes/our-staff'
import { Route as PricingTablesRouteImport } from './routes/pricing-tables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStaffRoute = OurStaffRouteImport.update({
  id: '/our-staff',
  path: '/our-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingTablesRoute = PricingTablesRouteImport.update({
  id: '/pricing-tables',
  path: '/pricing-tables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/our-staff': typeof OurStaffRoute
  '/pricing-tables': typeof PricingTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/our-staff': typeof OurStaffRoute
  '/pricing-tables': typeof PricingTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/our-staff': typeof OurStaffRoute
  '/pricing-tables': typeof PricingTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about-us' | '/our-staff' | '/pricing-tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-us' | '/our-staff' | '/pricing-tables'
  id: '__root__' | '/' | '/about-us' | '/our-staff' | '/pricing-tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  OurStaffRoute: typeof OurStaffRoute
  PricingTablesRoute: typeof PricingTablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-staff': {
      id: '/our-staff'
      path: '/our-staff'
      fullPath: '/our-staff'
      preLoaderRoute: typeof OurStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-tables': {
      id: '/pricing-tables'
      path: '/pricing-tables'
      fullPath: '/pricing-tables'
      preLoaderRoute: typeof PricingTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  OurStaffRoute: OurStaffRoute,
  PricingTablesRoute: PricingTablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
